apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-elearning
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /var/data
    server: 10.10.10.70

